# problems.py

import numpy as np

# Define a dictionary of system problems
problem_set = {
    1: {
        "A": np.array([[0, 2, -1],
                       [-1, -3, 0],
                       [2, 1, -2]]),
        "B": np.array([[1],
                       [0],
                       [1]]),
        "C": np.array([[1, 0, 0]]),
        "D": np.array([[0]]),
        "R": np.array([[-4.4461, 2.0000, 7.4461]]),
        "N": np.array([[15.2615]]),
        "L": np.array([[2322],
                       [1891],
                       [327]]),
        "spec-1": "Settling Time: 2s",
        "spec-2": "Overshoot: 10%",
    },
    2: {
        "A": np.array([[-2, 0, 1],
                       [1, -3, 2],
                       [0, 1, -1]]),
        "B": np.array([[0],
                       [1],
                       [1]]),
        "C": np.array([[0, 1, 0]]),
        "D": np.array([[0]]),
        "R": np.array([[39.4784,    1.0000,    1.0000]]),
        "N": np.array([[24.8448]]),
        "L": np.array([[465],
                       [527],
                       [98]]),
        "spec-1": "Peak Time: 0.5s",
        "spec-2": "Settling Time: 2s",
    },
    3: {
        "A": np.array([[-3, 1, 0],
                       [2, -1, 1],
                       [1, 0, -2]]),
        "B": np.array([[1],
                       [0],
                       [1]]),
        "C": np.array([[0, 0, 1]]),
        "D": np.array([[0]]),
        "R": np.array([[6.2928,    7.8761,   -1.6262]]),
        "N": np.array([[39.8175]]),
        "L": np.array([[973],
                       [803],
                       [21]]),
        "spec-1": "Settling Time: 1.5s",
        "spec-2": "Overshoot: 5%",
    },
    4: {
        "A": np.array([[0, 1, 2],
                       [2, -2, 1],
                       [1, 0, -3]]),
        "B": np.array([[1],
                       [1],
                       [0]]),
        "C": np.array([[1, 0, 0]]),
        "D": np.array([[0]]),
        "R": np.array([[19.8335,  -15.6231,   -6.5061]]),
        "N": np.array([[7.7630]]),
        "L": np.array([[3752],
                       [2802],
                       [515]]),
        "spec-1": "Peak Time: 1s",
        "spec-2": "Overshoot: 10%",
    },
    5: {
        "A": np.array([[-1, 2, 0],
                       [1, -2, 1],
                       [0, 1, -3]]),
        "B": np.array([[0],
                       [1],
                       [1]]),
        "C": np.array([[0, 1, 0]]),
        "D": np.array([[0]]),
        "R": np.array([[5.8909,    1.0000,    1.0000]]),
        "N": np.array([[12.7817]]),
        "L": np.array([[3870],
                       [2179],
                       [291]]),
        "spec-1": "Settling Time: 2s",
        "spec-2": "Overshoot: 12%",
    },
    6: {
        "A": np.array([[-3, 1, 2],
                       [2, -2, 1],
                       [-1, 0, -4]]),
        "B": np.array([[1],
                       [0],
                       [1]]),
        "C": np.array([[1, 0, 0]]),
        "D": np.array([[0]]),
        "R": np.array([[-0.9771,    6.9061,    3.9600]]),
        "N": np.array([[8.6849]]),
        "L": np.array([[3060],
                       [2034],
                       [315]]),
        "spec-1": "Peak Time: 1s",
        "spec-2": "Overshoot: 5%",
    },
    7: {
        "A": np.array([[-2, -1, 3],
                       [1, -3, -2],
                       [2, 1, -5]]),
        "B": np.array([[0],
                       [1],
                       [1]]),
        "C": np.array([[0, 1, 0]]),
        "D": np.array([[0]]),
        "R": np.array([[12.9728,   13.9728,  -13.9728]]),
        "N": np.array([[24.9547]]),
        "L": np.array([[1545],
                       [2170],
                       [214]]),
        "spec-1": "Settling Time: 1.6s",
        "spec-2": "Overshoot: 7%",
    },
    8: {
        "A": np.array([[-4, 2, -1],
                       [-3, -3, 1],
                       [0, 2, -3]]),
        "B": np.array([[1],
                       [1],
                       [0]]),
        "C": np.array([[0, 0, 1]]),
        "D": np.array([[0]]),
        "R": np.array([[18.9111,  -22.5111,  -22.9831]]),
        "N": np.array([[67.2615]]),
        "L": np.array([[-316],
                       [196],
                       [8]]),
        "spec-1": "Peak Time: 0.5s",
        "spec-2": "Settling Time: 2.5s",
    },
    9: {
        "A": np.array([[-1, 3, 2],
                       [-2, -3, 1],
                       [0, 1, -6]]),
        "B": np.array([[1],
                       [0],
                       [1]]),
        "C": np.array([[1, 0, 0]]),
        "D": np.array([[0]]),
        "R": np.array([[0.8609,    0.8226,   -0.8609]]),
        "N": np.array([[2.3468]]),
        "L": np.array([[4173],
                       [1618],
                       [153]]),
        "spec-1": "Settling Time: 1.6s",
        "spec-2": "Overshoot: 4%",
    },
    10: {
        "A": np.array([[-2, -1, 0],
                       [3, -4, 2],
                       [1, 2, -5]]),
        "B": np.array([[0],
                       [1],
                       [1]]),
        "C": np.array([[0, 1, 0]]),
        "D": np.array([[0]]),
        "R": np.array([[-7.8548,    1.8166,    0.0589]]),
        "N": np.array([[9.3029]]),
        "L": np.array([[6009],
                       [1644],
                       [109]]),
        "spec-1": "Peak Time: 1s",
        "spec-2": "Overshoot: 4%",
    },
    11: {
        "A": np.array([[-3, 2, -1],
                       [1, -5, 3],
                       [2, 0, -4]]),
        "B": np.array([[1],
                       [0],
                       [1]]),
        "C": np.array([[1, 0, 0]]),
        "D": np.array([[0]]),
        "R": np.array([[-2.8913,   11.6739,   -1.1087]]),
        "N": np.array([[8.2816]]),
        "L": np.array([[1619],
                       [681],
                       [70]])
    }
        
}
